'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','cs2career','web','static','app.js'),'utf8');
const start=source.indexOf('function activityGroups('),end=source.indexOf('\nfunction renderHome()',start);
const context={};vm.runInNewContext(source.slice(start,end),context);
const mine=['training','contract','shared'],world=Array.from({length:10},(_,i)=>'world '+i).concat(['shared']);
const result=context.activityGroups(mine,world);
assert.equal(result[0].title,'我的动态');assert.equal(result[1].title,'世界动态');
assert.equal(result[0].rows[0],'shared');assert.equal(result[0].rows[1],'contract');
assert.equal(result[1].rows.length,4);assert.equal(result[1].rows[0],'world 9');
assert.ok(!result[1].rows.includes('shared'),'Deduplicate the same system fact across sources');
assert.ok(result[0].rows.includes('training'),'A full world log cannot erase the player’s own activity');
const mailStart=source.indexOf('function visibleMailRows('),mailEnd=source.indexOf('\nfunction renderMail()',mailStart);
vm.runInNewContext(source.slice(mailStart,mailEnd),context);
const mailbox=[{id:'monthly',kind:'news',publication_key:'monthly:2026-01'},{id:'major',kind:'news',publication_key:'major:2026-a'},{id:'notice',kind:'notification'},{id:'contract',kind:'contract'}];
assert.deepEqual(Array.from(context.visibleMailRows({inbox:mailbox,assist:{quick_mode:true}}),row=>row.id),['contract','notice','major']);
assert.equal(context.visibleMailRows({inbox:mailbox,assist:{quick_mode:false}}).length,4,'Normal mode must retain monthly reports');
assert.equal(mailbox.length,4,'Quick-mode presentation must not delete saved monthly reports');
console.log('PASS: personal activity remains visible, per-source order preserved, world feed bounded, duplicate facts removed.');
