/* Isolated tactical editor contract and Chromium fixtures.
 * node tools/test_tactics_ui.cjs [--browser]
 * No career, CS2, plugin, official save or live service is touched.
 * Reuse CAREER_PLAYWRIGHT and CAREER_BROWSER_TEMP for existing runtime/cache.
 * CAREER_TACTICS_SCREENSHOT_MAP optionally selects a map for the QA screenshot.
 */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=path.resolve(__dirname,'../cs2career/web/static'),editor=require(path.join(base,'desk/tactics.js'));
const mapMetadata=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../cs2career/data/tactical_maps.json'),'utf8')).maps,meta=mapMetadata.de_dust2;
const draft=()=>editor.fresh();
function pure(){
  for(const finish of ['auto','hold','native']){const v=draft();v.slots[2].finish=finish;assert.equal(editor.parseImport(v).tactic.slots[2].finish,finish);}
  for(const finish of ['rush',null,1,{}]){const v=draft();v.slots[2].finish=finish;assert.throws(()=>editor.normalize(v));}
  const checked=editor.checkMeta(meta);assert.deepEqual(editor.pixelToWorld([0,0],checked),[-2476,3239]);
  assert.deepEqual(editor.pixelToWorld([1024,1024],meta),[2029.6000000000004,-1266.6000000000004]);
  for(const point of [[0,0],[512,512],[23.4,800.2]]){const pixel=editor.worldToPixel(editor.pixelToWorld(point,meta),meta);pixel.forEach((v,i)=>assert.ok(Math.abs(v-point[i])<1e-10));}
  for(const value of [null,{...meta,scale:0},{...meta,scale:NaN},{...meta,image:'javascript:alert(1)'},{...meta,height:0},{...meta,image:'https://example.com/de_dust2.png'},{...meta,image:'/tactical_maps/de_dust2.png?script=1'},{...meta,image:'/tactical_maps/../de_dust2.png'},{...meta,layers:[{id:'lower',name:'下层',image:'javascript:alert(1)'}]}])assert.throws(()=>editor.checkMeta(value));
  assert.equal(editor.maps.length,10);for(const {map} of editor.maps){const m=editor.checkMeta(mapMetadata[map],map);for(const point of [[0,0],[512,512],[1024,1024]])editor.worldToPixel(editor.pixelToWorld(point,m),m).forEach((v,i)=>assert.ok(Math.abs(v-point[i])<1e-9));}
  assert.throws(()=>editor.checkMeta(mapMetadata.de_nuke,'de_mirage'));assert.throws(()=>editor.checkMeta({...meta,layers:[{id:'lower',name:'下层',image:'/tactical_maps/de_nuke_lower.png'}]},'de_dust2'));
  const sample=draft();sample.slots[1].steps.push({position:[-2000,2000],wait:.05,level:'lower',movement:'run',look_at:[300,1400]});
  assert.deepEqual(editor.normalize(sample),sample);const defaults=draft();defaults.slots[0].steps=[{position:[1,2]}];assert.deepEqual(editor.normalize(defaults).slots[0].steps,[{position:[1,2],wait:0,level:'auto',movement:'run',look_at:null}]);
  const walking=structuredClone(sample);walking.slots[1].steps[0].movement='walk';assert.deepEqual(editor.normalize(walking),walking);assert.deepEqual(editor.parseImport({schema_version:1,map:'de_nuke',tactics:[walking]},'de_nuke').tactics,[walking],'walk and its separate arrival wait survive schema1 import');
  const legacy={id:'legacy',name:'旧战术',side:'t',slots:Array.from({length:5},(_,i)=>({slot:i+1,steps:[]}))};const legacyClean=editor.normalize(legacy);assert.equal(legacyClean.assignment,'roster');assert.equal(legacyClean.human_slot,1);assert.ok(legacyClean.slots.every(slot=>slot.duty==='auto'));assert.deepEqual(editor.parseImport({schema_version:1,map:'de_dust2',tactics:[legacy]}).tactics,[legacyClean]);
  const ability={...draft(),assignment:'ability',human_slot:4};ability.slots[0].duty='awp';ability.slots[1].duty='awp';ability.slots[2].duty='entry';ability.slots[3].duty='lurk';ability.slots[4].duty='igl';assert.deepEqual(editor.normalize(ability),ability,'repeated duties and a movable human slot are preserved');assert.deepEqual(editor.parseImport({map:'de_nuke',tactic:ability},'de_nuke').tactic,ability);
  for(const patch of [{assignment:'skills'},{assignment:null},{human_slot:0},{human_slot:6},{human_slot:'2'},{human_slot:null},{assignment:'roster',human_slot:2}])assert.throws(()=>editor.normalize({...ability,...patch}));for(const duty of ['sniper',null,2]){const invalid=structuredClone(ability);invalid.slots[0].duty=duty;assert.throws(()=>editor.normalize(invalid));}
  assert.equal(editor.fresh('ct',[{id:'my_tactic'},{id:'my_tactic_2'}]).id,'my_tactic_3');
  for(const value of [null,[],{...sample,id:'../pwn'},{...sample,id:'UPPER'},{...sample,id:'a'.repeat(33)},{...sample,name:' '},{...sample,name:'n'.repeat(41)},{...sample,side:'both'},{...sample,slots:sample.slots.slice(0,4)},{...sample,slots:[sample.slots[0],...sample.slots.slice(0,4)]}])assert.throws(()=>editor.normalize(value));
  for(const step of [{position:[1]},{position:[1,'2']},{position:[NaN,2]},{position:[1,2],wait:-1},{position:[1,2],wait:31},{position:[1,2],wait:'1'},{position:[1,2],level:'sky'},{position:[1,2],movement:'crouch'},{position:[1,2],movement:null},{position:[1,2],movement:1},{position:[1,2],look_at:[1,2,3]}]){const value=draft();value.slots[0].steps=[step];assert.throws(()=>editor.normalize(value));}
  const full=draft();full.slots[4].steps=Array.from({length:12},()=>({position:[1,2],wait:30,level:'upper',look_at:null}));assert.equal(editor.normalize(full).slots[4].steps.length,12);full.slots[4].steps.push({position:[1,2]});assert.throws(()=>editor.normalize(full));
  assert.deepEqual(editor.parseImport(sample),{map:'de_dust2',tactic:sample});assert.deepEqual(editor.parseImport({tactic:sample}),{map:'de_dust2',tactic:sample});
  assert.deepEqual(editor.parseImport(sample,'de_mirage'),{map:'de_mirage',tactic:sample});assert.deepEqual(editor.parseImport({map:'de_mirage',tactic:sample},'de_mirage'),{map:'de_mirage',tactic:sample});
  assert.deepEqual(editor.parseImport({schema_version:1,map:'de_dust2',tactics:[sample]}),{schema_version:1,map:'de_dust2',tactics:[sample]});
  assert.deepEqual(editor.parseImport({schema_version:1,map:'de_mirage',tactics:[sample]},'de_mirage'),{schema_version:1,map:'de_mirage',tactics:[sample]});
  assert.throws(()=>editor.parseImport({schema_version:2,map:'de_dust2',tactics:[]}));assert.throws(()=>editor.parseImport({schema_version:1,map:'de_mirage',tactics:[]}));assert.throws(()=>editor.parseImport({map:'de_nuke',tactic:sample},'de_mirage'));assert.throws(()=>editor.parseImport({schema_version:1,map:'de_dust2',tactics:[sample,sample]}));
  const injected={...sample,name:'<img src=x onerror=alert(1)>',unknown:'strip'};assert.equal(editor.normalize(injected).name,injected.name);assert.equal(editor.normalize(injected).unknown,undefined);
  const index=fs.readFileSync(path.join(base,'index.html'),'utf8');for(const entry of ['data-view="tactics"','id="view-tactics"','desk/tactics.js','desk/tactics.css'])assert.ok(index.includes(entry));
  assert.match(fs.readFileSync(path.join(base,'desk/navigation.js'),'utf8'),/tactics:'战术编辑器'/);
  console.log('PASS: normalized five-slot contract, all defaults, identity-independent routes, bounds, map coordinates, import variants and static route injection.');
}
async function browser(){
  if(process.env.CAREER_BROWSER_TEMP){process.env.TEMP=process.env.CAREER_BROWSER_TEMP;process.env.TMP=process.env.CAREER_BROWSER_TEMP;}
  const {chromium}=require(process.env.CAREER_PLAYWRIGHT||'playwright'),browser=await chromium.launch({channel:'chrome',headless:true});
  try{
    const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],calls=[],dialogs=[],failMaps=new Set();let reads=0,failRead=false,mapFailures=1,acceptDialogs=true;
    const initial=draft();initial.id='saved_demo';initial.name='<img src=x onerror=window.pwned=1>';initial.side='ct';initial.slots[2].steps=[{position:[-1000,1600],wait:0,level:'auto',look_at:null}];
    let library=[initial];const libraries=Object.fromEntries(editor.maps.map(row=>[row.map,[]]));page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{dialogs.push(d.message());await (acceptDialogs?d.accept():d.dismiss());});
    await page.route('http://tactics.test/**',async route=>{
      const request=route.request(),url=new URL(request.url());
      if(url.pathname==='/api/tactics'&&request.method()==='GET'){reads++;const map=url.searchParams.get('map')||'de_dust2';if(failRead||failMaps.has(map)){await route.fulfill({status:503,contentType:'application/json',body:'{"msg":"fixture unavailable"}'});return;}await route.fulfill({contentType:'application/json',body:JSON.stringify({schema_version:1,map,map_meta:mapMetadata[map],tactics:map==='de_dust2'?library:libraries[map],available_maps:editor.maps,slot_labels:['你 · 手动操作','队友1','队友2','队友3','队友4'],runtime_note:'地图战术：分路、到点等待与箭头观察；交火优先原生 AI，下包后 T 守包、CT 回防。仅正式准备阶段选战术，不控制真人。'})});return;}
      if(url.pathname.startsWith('/api/tactics/')){const body=request.postDataJSON(),map=url.searchParams.get('map')||body.map||'de_dust2';calls.push({path:url.pathname,map,body});let rows=map==='de_dust2'?library:libraries[map];if(url.pathname.endsWith('/save')){const t=editor.normalize(body.tactic);rows=[...rows.filter(row=>row.id!==t.id),t];}if(url.pathname.endsWith('/import')){const data=editor.parseImport(body,map),incoming=data.tactic?[data.tactic]:data.tactics;for(const t of incoming)rows=[...rows.filter(row=>row.id!==t.id),t];}if(url.pathname.endsWith('/delete'))rows=rows.filter(row=>row.id!==body.id);if(map==='de_dust2')library=rows;else libraries[map]=rows;await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,map,tactics:rows})});return;}
      if(url.pathname.startsWith('/tactical_maps/')){if(url.pathname===meta.image&&mapFailures-->0){await route.abort('failed');return;}const actual=path.join(base,url.pathname.slice(1));await route.fulfill({contentType:'image/png',body:fs.readFileSync(fs.existsSync(actual)?actual:path.join(base,'tactical_maps/de_dust2.png'))});return;}
      await route.fulfill({contentType:'text/html',body:'<!doctype html><html><body><div class="app"><aside class="side">Fixture</aside><main class="main"><section class="view on" id="view-tactics"></section></main></div></body></html>'});
    });
    await page.goto('http://tactics.test');
    for(const file of ['style.css','desk.css','theme.css','desk/tactics.css'])await page.addStyleTag({content:fs.readFileSync(path.join(base,file),'utf8')});
    await page.addScriptTag({content:'window.CareerUI={pages:{}};window.get=async url=>{const r=await fetch(url);if(!r.ok)throw new Error("read failed");return r.json();};window.post=async(url,body,options)=>{window.lastPostOptions=options;const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return r.json();};'});
    for(const file of ['desk/i18n.js','desk/tactics.js'])await page.addScriptTag({content:fs.readFileSync(path.join(base,file),'utf8')});
    await page.evaluate(async()=>{const host=document.querySelector('#view-tactics');window.controller=CareerTactics.mount(host);await controller.load();});await page.waitForFunction(()=>document.querySelector('[data-tactic-status]').textContent.includes('图片加载失败'));assert.equal(await page.evaluate(()=>controller.state.mapReady),false);await page.locator('[data-tactic-refresh]').click();await page.waitForFunction(()=>controller.state.mapReady);
    assert.equal(reads,2);assert.equal(await page.locator('[data-tactic-slot="2"]').getAttribute('aria-pressed'),'true');assert.match(await page.locator('.tactics-slot-note').innerText(),/槽 1 是你/);assert.match(await page.locator('[data-tactic-slot="1"]').innerText(),/手动/);assert.equal(await page.evaluate(()=>window.pwned),undefined);assert.equal(await page.locator('[data-tactic-library] img').count(),0);
    assert.equal(await page.locator('[data-tactic-assignment]').inputValue(),'roster');assert.equal(await page.locator('[data-tactic-human-slot]').isDisabled(),true);assert.equal(await page.locator('[data-tactic-duty]').count(),5);assert.equal(await page.locator('[data-tactic-duty="2"]').isDisabled(),false);
    await page.locator('[data-tactic-load="saved_demo"]').click();assert.equal(dialogs.length,0,'unchanged blank draft does not ask discard');assert.equal(await page.locator('[data-tactic-slot="3"]').getAttribute('aria-pressed'),'true');
    await page.locator('[data-tactic-step="0"]').click();assert.equal(await page.locator('[data-tactic-movement]').inputValue(),'run','legacy steps default to run');assert.match(await page.locator('[data-tactic-step="0"]').innerText(),/跑步/);
    await page.locator('[data-tactic-new]').click();await page.locator('[data-tactic-id]').fill('test_route');await page.locator('[data-tactic-name]').fill('小道路线');await page.locator('[data-tactic-side]').selectOption('t');
    const svg=page.locator('[data-tactic-svg]');async function point(x,y){await svg.scrollIntoViewIfNeeded();const box=await svg.boundingBox();return {x:box.x+box.width*x/1024,y:box.y+box.height*y/1024};}async function mapClick(x,y){const p=await point(x,y);await page.mouse.click(p.x,p.y);}
    await mapClick(210,300);let value=await page.evaluate(()=>controller.state.draft);const expected=editor.pixelToWorld([210,300],meta);value.slots[1].steps[0].position.forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<.01));
    assert.equal(value.slots[1].steps[0].movement,'run','new steps default to run');assert.equal(await page.locator('[data-tactic-movement]').inputValue(),'run');assert.match(await page.locator('[data-tactic-movement]').locator('..').innerText(),/到当前点/);assert.match(await page.locator('[data-tactic-wait]').locator('..').innerText(),/到点后等待/);await page.locator('[data-tactic-movement]').selectOption('walk');assert.equal(await page.evaluate(()=>controller.state.draft.slots[1].steps[0].wait),0,'movement choice does not alter arrival wait');assert.match(await page.locator('[data-tactic-step="0"]').innerText(),/静步/);
    await page.locator('[data-tactic-wait]').fill('0.05');assert.equal(await page.locator('[data-tactic-wait]').evaluate(e=>e.checkValidity()),true);await page.locator('[data-tactic-level]').selectOption('lower');
    await page.locator('[data-tactic-look-set]').click();await mapClick(380,330);value=await page.evaluate(()=>controller.state.draft.slots[1].steps[0]);assert.equal(value.wait,.05);assert.equal(value.level,'lower');assert.ok(value.look_at);
    await mapClick(500,550);assert.equal(await page.locator('[data-tactic-movement]').inputValue(),'run','each newly added segment defaults independently');await page.locator('[data-tactic-up]').click();value=await page.evaluate(()=>controller.state.draft.slots[1].steps);assert.equal(value[1].level,'lower');assert.equal(value[1].movement,'walk','reorder moves the destination movement with its step');assert.match(await page.locator('[data-tactic-step="0"]').innerText(),/经过点（不停留）/);await page.locator('[data-tactic-down]').click();assert.match(await page.locator('[data-tactic-step="1"]').innerText(),/最终到点/);
    const a=await point(500,550),b=await point(530,570);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:6});await page.mouse.up();value=await page.evaluate(()=>controller.state.draft.slots[1].steps[1].position);editor.pixelToWorld([530,570],meta).forEach((v,i)=>assert.ok(Math.abs(value[i]-v)<.1));
    await page.locator('[data-tactic-copy-to]').selectOption('all');await page.locator('[data-tactic-copy]').click();assert.equal(await page.evaluate(()=>controller.state.draft.slots.every(s=>s.steps.length===2)),true);
    assert.equal(await page.evaluate(()=>controller.state.draft.slots.every(s=>s.steps[0].movement==='walk'&&s.steps[1].movement==='run')),true,'copy retains every segment movement');await page.locator('[data-tactic-movement]').selectOption('walk');assert.equal(await page.evaluate(()=>controller.state.draft.slots[0].steps[1].movement),'run','copied movement settings remain independent');
    await page.locator('[data-tactic-wait]').fill('3');assert.equal(await page.evaluate(()=>controller.state.draft.slots[0].steps[1].wait),0,'copied routes are independent');
    await page.locator('[data-tactic-step="0"]').click();await page.locator('[data-tactic-look-clear]').click();assert.equal(await page.evaluate(()=>controller.state.draft.slots[1].steps[0].look_at),null);await page.locator('[data-tactic-save]').click();await page.waitForFunction(()=>!controller.state.busy);assert.equal(calls[0].path,'/api/tactics/save');assert.equal(calls[0].body.tactic.id,'test_route');assert.equal(calls[0].body.tactic.slots.length,5);assert.equal(calls[0].body.tactic.slots[1].steps[0].wait,.05);assert.deepEqual(await page.evaluate(()=>lastPostOptions),{render:false,quiet:true});
    assert.equal(calls[0].body.map,'de_dust2');
    assert.equal(calls[0].body.tactic.slots[1].steps[0].movement,'walk');
    await page.evaluate(()=>{window.selectIdentity=document.querySelector('[data-tactic-level]');window.mapSelectIdentity=document.querySelector('[data-tactic-map-select]');window.mapOptionIdentity=mapSelectIdentity.options[0];window.CareerUI.pages.tactics({view:'tactics'},document.querySelector('#view-tactics'),()=>true);});await page.locator('[data-tactic-step="0"]').click();await page.locator('[data-tactic-level]').focus();
    const oldReads=reads;await page.evaluate(async()=>{for(let i=0;i<5;i++)await CareerUI.pages.tactics({view:'tactics'},document.querySelector('#view-tactics'),()=>true);});assert.equal(reads,oldReads);assert.equal(await page.evaluate(()=>selectIdentity===document.querySelector('[data-tactic-level]')&&document.activeElement===selectIdentity),true,'poll renders preserve select identity and focus');
    await page.locator('[data-tactic-movement]').focus();await page.evaluate(()=>{window.movementIdentity=document.querySelector('[data-tactic-movement]');window.movementOptionIdentity=movementIdentity.options[1];});await page.evaluate(async()=>{for(let i=0;i<5;i++)await CareerUI.pages.tactics({view:'tactics'},document.querySelector('#view-tactics'),()=>true);});assert.equal(await page.evaluate(()=>movementIdentity===document.querySelector('[data-tactic-movement]')&&movementOptionIdentity===movementIdentity.options[1]&&document.activeElement===movementIdentity&&movementIdentity.value==='walk'),true,'poll renders preserve movement select, options, focus and selection');
    await page.locator('[data-tactic-assignment]').selectOption('ability');await page.locator('[data-tactic-human-slot]').selectOption('4');await page.locator('[data-tactic-duty="2"]').selectOption('awp');await page.locator('[data-tactic-duty="3"]').selectOption('awp');assert.equal(await page.locator('[data-tactic-human-slot]').isDisabled(),false);assert.match(await page.locator('[data-tactic-slot="4"]').innerText(),/手动/);assert.doesNotMatch(await page.locator('[data-tactic-slot="1"]').innerText(),/手动/);assert.match(await page.locator('[data-tactic-economy-note]').innerText(),/双狙.*正常经济/);
    await page.evaluate(()=>{window.dutyIdentity=document.querySelector('[data-tactic-duty="2"]');window.dutyOptionIdentity=dutyIdentity.options[1];window.assignmentIdentity=document.querySelector('[data-tactic-assignment]');window.humanIdentity=document.querySelector('[data-tactic-human-slot]');});await page.locator('[data-tactic-duty="2"]').focus();await page.evaluate(async()=>{for(let i=0;i<5;i++)await CareerUI.pages.tactics({view:'tactics'},document.querySelector('#view-tactics'),()=>true);});assert.equal(await page.evaluate(()=>dutyIdentity===document.querySelector('[data-tactic-duty="2"]')&&dutyOptionIdentity===dutyIdentity.options[1]&&assignmentIdentity===document.querySelector('[data-tactic-assignment]')&&humanIdentity===document.querySelector('[data-tactic-human-slot]')&&document.activeElement===dutyIdentity),true,'duty controls preserve nodes, options and focus on polling');
    await page.locator('[data-tactic-save]').click();await page.waitForFunction(()=>!controller.state.busy);const abilitySaved=calls.at(-1).body.tactic;assert.equal(abilitySaved.assignment,'ability');assert.equal(abilitySaved.human_slot,4);assert.equal(abilitySaved.slots[1].duty,'awp');assert.equal(abilitySaved.slots[2].duty,'awp');await page.locator('[data-tactic-load="test_route"]').click();assert.equal(await page.locator('[data-tactic-human-slot]').inputValue(),'4');assert.equal(await page.locator('[data-tactic-duty="3"]').inputValue(),'awp');
    const abilityDownload=page.waitForEvent('download');await page.locator('[data-tactic-export]').click();assert.deepEqual(JSON.parse(fs.readFileSync(await (await abilityDownload).path(),'utf8')).tactic,abilitySaved,'ability duties survive export');
    await page.locator('[data-tactic-assignment]').selectOption('roster');assert.equal(await page.evaluate(()=>controller.state.draft.human_slot),1);assert.equal(await page.locator('[data-tactic-human-slot]').isDisabled(),true);assert.equal(await page.locator('[data-tactic-duty="2"]').isDisabled(),false);assert.equal(await page.locator('[data-tactic-duty="2"]').inputValue(),'awp','roster mode keeps effective duties visible and editable');assert.match(await page.locator('[data-tactic-slot="1"]').innerText(),/手动/);await page.locator('[data-tactic-save]').click();await page.waitForFunction(()=>!controller.state.busy);
    await page.locator('[data-tactic-map-select]').focus();await page.evaluate(async()=>{for(let i=0;i<5;i++)await CareerUI.pages.tactics({view:'tactics'},document.querySelector('#view-tactics'),()=>true);});assert.equal(await page.evaluate(()=>mapSelectIdentity===document.querySelector('[data-tactic-map-select]')&&mapOptionIdentity===mapSelectIdentity.options[0]&&document.activeElement===mapSelectIdentity),true,'poll renders preserve map selector, options and focus');
    assert.equal(await page.locator('[data-tactic-map-select] option').count(),10);assert.equal(await page.locator('[data-tactic-radar-controls]').isVisible(),false);
    await page.locator('[data-tactic-filter]').selectOption('ct');assert.equal(await page.locator('[data-tactic-load="test_route"]').count(),0);await page.locator('[data-tactic-filter]').selectOption('all');
    const mapSelect=page.locator('[data-tactic-map-select]');
    async function switchMap(map){await mapSelect.selectOption(map);await page.waitForFunction(map=>controller.state.map===map&&!controller.state.busy&&controller.state.mapReady,map);}
    await page.locator('[data-tactic-name]').fill('未保存的沙二路线');const retained=await page.evaluate(()=>JSON.stringify({map:controller.state.map,draft:controller.state.draft,meta:controller.state.meta,list:controller.state.list})),beforeCancelReads=reads;
    acceptDialogs=false;await mapSelect.selectOption('de_mirage');assert.equal(reads,beforeCancelReads,'cancelled dirty map switch does not read');assert.equal(await mapSelect.inputValue(),'de_dust2');assert.equal(await page.evaluate(()=>JSON.stringify({map:controller.state.map,draft:controller.state.draft,meta:controller.state.meta,list:controller.state.list})),retained,'cancelled switch retains draft and coordinates');acceptDialogs=true;
    failMaps.add('de_mirage');await mapSelect.selectOption('de_mirage');await page.waitForFunction(()=>document.querySelector('[data-tactic-status]').textContent.includes('read failed')&&!controller.state.busy);assert.equal(await mapSelect.inputValue(),'de_dust2');assert.equal(await page.evaluate(()=>JSON.stringify({map:controller.state.map,draft:controller.state.draft,meta:controller.state.meta,list:controller.state.list})),retained,'failed switch commits none of the map response');failMaps.delete('de_mirage');
    await switchMap('de_mirage');assert.equal(await page.locator('[data-tactic-load="test_route"]').count(),0);assert.equal(await page.evaluate(()=>controller.state.originalId),null);assert.equal(await page.evaluate(()=>controller.state.draft.slots.every(s=>!s.steps.length)),true);assert.equal(await page.locator('[data-tactic-image]').getAttribute('alt'),'Mirage');
    await page.locator('[data-tactic-id]').fill('test_route');await page.locator('[data-tactic-name]').fill('Mirage路线');await mapClick(630,290);await page.locator('[data-tactic-save]').click();await page.waitForFunction(()=>!controller.state.busy);const mirageSaved=calls.at(-1);assert.equal(mirageSaved.body.map,'de_mirage');const miragePoint=mirageSaved.body.tactic.slots[1].steps[0].position;editor.pixelToWorld([630,290],mapMetadata.de_mirage).forEach((v,i)=>assert.ok(Math.abs(v-miragePoint[i])<.1));assert.equal(library.find(t=>t.id==='test_route').name,'小道路线','same ID remains separate on Dust II');
    async function exportAndRead(selector){const pending=page.waitForEvent('download');await page.locator(selector).click();const file=await pending;return {name:file.suggestedFilename(),value:JSON.parse(fs.readFileSync(await file.path(),'utf8'))};}
    const currentExport=await exportAndRead('[data-tactic-export]');assert.equal(currentExport.name,'mirage-test_route.json');assert.equal(currentExport.value.map,'de_mirage');assert.equal(currentExport.value.tactic.id,'test_route');assert.deepEqual(currentExport.value.tactic.slots[1].steps[0].position,miragePoint);
    const mirageExport=await exportAndRead('[data-tactic-export-all]');assert.equal(mirageExport.name,'mirage-tactics.json');assert.equal(mirageExport.value.map,'de_mirage');assert.equal(mirageExport.value.tactics.length,1);
    const beforeForeignImport=calls.length;for(const foreign of [{map:'de_dust2',tactic:draft()},{schema_version:1,map:'de_dust2',tactics:[draft()]}]){await page.locator('[data-tactic-file]').setInputFiles({name:'foreign.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(foreign))});await page.waitForFunction(()=>!controller.state.busy);assert.match(await page.locator('[data-tactic-status]').innerText(),/请先选择对应地图/);}assert.equal(calls.length,beforeForeignImport,'foreign map coordinates never reach import endpoint');assert.equal(await page.evaluate(()=>controller.state.draft.name),'Mirage路线');
    await switchMap('de_nuke');assert.equal(await page.locator('[data-tactic-radar-controls]').isVisible(),true);await mapClick(440,440);await page.locator('[data-tactic-level]').selectOption('lower');const lowerStep=await page.evaluate(()=>JSON.stringify(controller.state.draft.slots[1].steps[0]));await page.locator('[data-tactic-radar]').selectOption('lower');await page.waitForFunction(()=>controller.state.mapReady&&document.querySelector('[data-tactic-image]').dataset.mapSource.endsWith('de_nuke_lower.png'));assert.equal(await page.evaluate(()=>JSON.stringify(controller.state.draft.slots[1].steps[0])),lowerStep,'lower radar preserves saved step level and position');await page.locator('[data-tactic-radar]').selectOption('upper');await page.waitForFunction(()=>controller.state.mapReady&&document.querySelector('[data-tactic-image]').dataset.mapSource.endsWith('de_nuke.png'));assert.equal(await page.evaluate(()=>JSON.stringify(controller.state.draft.slots[1].steps[0])),lowerStep,'upper radar does not relabel lower step');
    await switchMap('de_train');assert.equal(await page.locator('[data-tactic-radar] option[value="lower"]').count(),1);await switchMap('de_vertigo');assert.equal(await page.locator('[data-tactic-radar] option[value="lower"]').count(),1);await switchMap('de_dust2');assert.equal(await page.locator('[data-tactic-radar-controls]').isVisible(),false);await page.locator('[data-tactic-load="test_route"]').click();assert.equal(await page.locator('[data-tactic-name]').inputValue(),'小道路线');assert.deepEqual(await page.evaluate(()=>controller.state.draft.slots[1].steps[0].position),calls[0].body.tactic.slots[1].steps[0].position);
    await switchMap('de_mirage');await page.locator('[data-tactic-load="test_route"]').click();assert.deepEqual(await page.evaluate(()=>controller.state.draft.slots[1].steps[0].position),miragePoint);await switchMap('de_dust2');
    const imported=draft();imported.id='imported';imported.name='<svg onload=window.pwned=2>';imported.side='ct';imported.assignment='ability';imported.human_slot=5;imported.slots[0].duty='awp';imported.slots[1].duty='awp';await page.locator('[data-tactic-file]').setInputFiles({name:'sample.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.waitForFunction(()=>!controller.state.busy);assert.equal(calls.at(-1).path,'/api/tactics/import');assert.equal(calls.at(-1).body.map,'de_dust2');assert.equal(calls.at(-1).map,'de_dust2');assert.equal(await page.evaluate(()=>controller.state.draft.id),'imported');assert.equal(await page.locator('[data-tactic-assignment]').inputValue(),'ability');assert.equal(await page.locator('[data-tactic-human-slot]').inputValue(),'5');assert.equal(await page.locator('[data-tactic-duty="1"]').inputValue(),'awp');assert.equal(await page.locator('[data-tactic-duty="2"]').inputValue(),'awp');assert.equal(await page.evaluate(()=>window.pwned),undefined);assert.equal(await page.locator('[data-tactic-library] svg').count(),0);
    imported.slots[1].steps=[{position:[-1000,1200],level:'auto',wait:4,movement:'walk',look_at:null}];await page.locator('[data-tactic-file]').setInputFiles({name:'same.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.waitForFunction(()=>!controller.state.busy);assert.ok(dialogs.some(d=>d.includes('覆盖已有战术')));await page.locator('[data-tactic-step="0"]').click();assert.equal(await page.locator('[data-tactic-movement]').inputValue(),'walk','import preserves walk on the destination segment');assert.equal(await page.locator('[data-tactic-wait]').inputValue(),'4','import preserves independent arrival wait');
    const total=calls.length;await page.locator('[data-tactic-file]').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"id":"<svg>","side":"t"}')});await page.waitForFunction(()=>!controller.state.busy);assert.equal(calls.length,total,'invalid imported ID never reaches server');
    const dl=page.waitForEvent('download');await page.locator('[data-tactic-export-all]').click();const download=await dl;assert.equal(download.suggestedFilename(),'dust2-tactics.json');const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(exported.map,'de_dust2');assert.equal(exported.schema_version,1);assert.equal(exported.tactics.length,library.length);
    assert.equal(exported.tactics.find(t=>t.id==='imported').slots[1].steps[0].movement,'walk','library export retains walk');
    await page.locator('[data-tactic-delete]').click();await page.waitForFunction(()=>!controller.state.busy);assert.equal(calls.at(-1).path,'/api/tactics/delete');assert.equal(calls.at(-1).body.id,'imported');assert.equal(await page.locator('[data-tactic-load="imported"]').count(),0);
    const partial={...draft(),id:'read_fail',name:'导入后刷新失败'};failRead=true;await page.locator('[data-tactic-file]').setInputFiles({name:'partial.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(partial))});await page.waitForFunction(()=>!controller.state.busy);assert.equal(await page.evaluate(()=>controller.state.draft.id),'read_fail');assert.match(await page.locator('[data-tactic-status]').innerText(),/已导入，但列表刷新失败/);failRead=false;
    await page.locator('[data-tactic-load="test_route"]').click();failRead=true;await page.locator('[data-tactic-delete]').click();await page.waitForFunction(()=>!controller.state.busy);assert.match(await page.locator('[data-tactic-status]').innerText(),/已删除，但列表刷新失败/);assert.equal(await page.locator('[data-tactic-load="test_route"]').count(),0);failRead=false;
    await page.locator('[data-tactic-slot="2"]').click();await mapClick(420,420);await page.locator('[data-tactic-look-set]').click();await page.evaluate(()=>CareerI18n.setLocale('en'));assert.match(await page.locator('[data-tactic-look-set]').innerText(),/Cancel marking/);await page.locator('[data-tactic-look-set]').click();assert.match(await page.locator('[data-tactic-look-set]').innerText(),/Set look direction/);assert.match(await page.locator('[data-tactic-runtime]').innerText(),/^Map tactics:/);assert.match(await page.locator('.tactics-map-selector').innerText(),/Map/);assert.match(await page.locator('[data-tactic-movement]').locator('..').innerText(),/Travel to this point/);assert.equal(await page.locator('[data-tactic-movement] option[value="run"]').innerText(),'Run (default)');assert.equal(await page.locator('[data-tactic-movement] option[value="walk"]').innerText(),'Walk quietly');assert.match(await page.locator('[data-tactic-wait]').locator('..').innerText(),/Wait after arrival/);assert.match(await page.locator('.tactics-movement-note').innerText(),/segment leading to this destination.*wait starts after arrival/);
    for(const width of [1280,736,420]){await page.setViewportSize({width,height:720});assert.equal(await page.locator('.tactics-layout').evaluate(el=>el.scrollWidth<=el.clientWidth+1&&el.getBoundingClientRect().right<=innerWidth+1),true,'layout contained at '+width);}
    if(process.env.CAREER_TACTICS_SCREENSHOT){const selected=process.env.CAREER_TACTICS_SCREENSHOT_MAP||'de_dust2';let id='split_test';if(selected==='de_dust2')library=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../cs2career/data/tactical_playbook.json'),'utf8')).tactics;else{const preview=draft();id=preview.id='map_preview';preview.name=mapMetadata[selected].name+' 路线';preview.slots[1].steps=[[430,540],[550,440],[680,320]].map(pixel=>({position:editor.pixelToWorld(pixel,mapMetadata[selected]),wait:1,level:'auto',look_at:editor.pixelToWorld([700,400],mapMetadata[selected])}));libraries[selected]=[preview];}await page.setViewportSize({width:1280,height:720});await page.evaluate(async map=>{CareerI18n.setLocale('zh-CN');await controller.load(map);},selected);await page.waitForFunction(()=>controller.state.mapReady&&!controller.state.busy);await page.locator('[data-tactic-load="'+id+'"]').click();await page.locator('[data-tactic-slot="2"]').click();await page.locator('[data-tactic-step="0"]').click();await page.evaluate(()=>scrollTo(0,0));fs.mkdirSync(path.dirname(process.env.CAREER_TACTICS_SCREENSHOT),{recursive:true});await page.screenshot({path:process.env.CAREER_TACTICS_SCREENSHOT});console.log('Screenshot:',process.env.CAREER_TACTICS_SCREENSHOT);}
    assert.deepEqual(errors,[]);console.log('PASS: isolated Chromium run/walk segment defaults, copy/reorder/save-load/import-export, independent arrival waits and stable movement dropdown; map isolation, radar layers, routes, duties, translations and 1280/736/420 containment.');
  }finally{await browser.close();}
}
(async()=>{pure();if(process.argv.includes('--browser'))await browser();})().catch(error=>{console.error(error);process.exitCode=1;});
